  <div  style="width:940px;    float:left; padding:10px; background-color : White">
        <h2>The PnET-Succession model and its interface</h2>
           
         <div  style="float:left; padding:10px; background-color : White">
             
             <img   src="resources/lui.png" border="1" />
             <!--<p>Click to enlarge</p>-->
             
             
              
         </div>
        
          <p>
          
             When I started using <a href="http://www.landis-ii.org/">LANDIS-II</a>   for my research at Purdue University, I was unsatisfied with the common practice to use predictions 
              of tree growth and biomass by the <a href="http://www.pnet.sr.unh.edu/">PnET</a>  model as input for LANDIS-II because it ignored a lot of information that was generated by the LANDIS-II model
              and should feed back into the PnET model. As an alternative, I incorporated the PnET model into LANDIS-II. The resulting <a href="http://www.landis-ii.org/extensions/pnet-succession">PnET-Succession</a> model 
           proved to be a very fertile approach with users from Harvard University, the Food and Agricultural Organisation of the United Nations and the USDA forest service. 
              
           The name PnET-Succession comes from the PnET model, that predicts foliage cover and biomass and the <a href="http://www.landis-ii.org/extensions/biomass-succession">LANDIS-II biomass succession</a> 
            extension that predicts forest how trees compete and what species, under which circumstances, is most likely to dominate the future of a 
           forest. 
              
           <br><br>
           The LANDIS-II model did not have an interface that was suitable to use with PnET-Succession. To facilitate simulations with PnET-Succession, 
           I developed a simple user interface. The interface (image) is a windows forms application with a file tree (on the left) and a workspace (on the right) that allows you 
              to view various types of output files. 
           
           When you add a scenario, the interface will add all associated input files to the file tree. 
            
          The interface will add additional simulation output files to the file tree when the user starts a simulation.
           
           The user can drag these output files from the file tree into the workspace where the interface creates dockable windows that allow the user to view the model outputs in various formats. 
            
          
 </p>
     <i>Graphics: Landis User Interface, left file view, right workspace. </i>
     <br><br>
   </div>
   